import 'package:erato/Signin_screen.dart';
import 'package:erato/firebase_options.dart';
import 'package:erato/home_screen.dart';
import 'package:erato/onboarding_pages/mainpage.dart';
import 'package:erato/UserProfile_And_Community/profile_page.dart';
import 'package:erato/services/firebase_api.dart';
import 'package:erato/services/notification.dart';
import 'package:erato/signup-screen.dart';
import 'package:erato/signup_secondscreen.dart';
import 'package:erato/splash_Screen.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
// core Flutter primitives
import 'package:flutter/foundation.dart';
// core FlutterFire dependency

// generated by 

final navigatorKey=GlobalKey<NavigatorState>(); 
RemoteMessage? message = ModalRoute.of(navigatorKey.currentContext!)!.settings.arguments as RemoteMessage?;
 Future<void> main()async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await FirebaseAPI().init_Notifications();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      darkTheme: ThemeData.dark(),
      title: 'Flutter Demo',
      theme: ThemeData(
       
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
        
        
      ),
      home: const SplashScreen(),
      navigatorKey: navigatorKey,
      routes: {
        '/signin': (context) => SignInScreen(),
        '/Profile':(context)=> ProfilePage(),
        '/signup':(context)=> SignUpScreen(),
        '/signup-second':(context)=> SignUppagetwo(),
        '/onboarding':(context)=> MainPage(),
        '/home':(context)=> HomeScreen(),
        '/notifications':(context)=> const NotificationsScreen(RemoteMessage()),
      },
    );
  }
}
